export { default as Number } from "./Number";
export { default as TextArea } from "./TextArea";
export { default as None } from "./None";
export { default as Answertype } from "./None";
export { default as Text } from "./Text";
export { default as Select } from "./Select";
export { default as Checkbox } from "./Checkbox";
export { default as Radio } from "./Radio";
export { default as Slider } from "./Slider";
